# Generated by Django 4.2.4 on 2023-08-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publish_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='custom_id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('sci', 'scientific'), ('', 'Python')], max_length=3),
        ),
    ]
