# Generated by Django 4.2.4 on 2023-08-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_publish_date_post_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('sci', 'scientific'), ('py', 'python')], max_length=3),
        ),
    ]
